language: node_js
node_js:
  - "0.10"

env:
  global:
  - COVERALLS_SERVICE_NAME=travis-ci
  # COVERALLS_REPO_TOKEN (encrypted)
  - secure: Lvxn4BqPgS53cFczusKswr7F0hjHJTaLqeKlQQ1xERLq8etmUoeejbpup1SY7iHRlVglhXm+uM9yeesDZt2H0+K3YXteJZRjE0a/WFu5utO+swSC6gTCxja9Sd9o6HXXxN5NXHP2mOAXZgTPetgzktXM+VV0wiZ/PsP90DPy7k8=

install:
  - cd ngsi_adapter/src
  - npm install
  - npm install -g grunt-cli
  - npm install coveralls --save 

after_success:
  - grunt coverage-report && cat site/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
